server:
  port: 8002
  servlet:
    context-path: /emp-mgmt
spring:
  datasource:
    username: root
    password: welcome
    url: jdbc:h2:mem:emp_db
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true