server:
  port: 8002

spring:
  datasource:
    username: sa
    password: welcome
    url: jdbc:h2:mem:emp_db

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
